<?php
$layoutPath = 'k:\desarrollo\medflow\resources\views\layouts\modern.blade.php';
$content = file_get_contents($layoutPath);

// 1. Reduce parent font-size in the chat box container
$oldChatBoxDef = '<div class="card-body bg-light" id="flowyChatBox" style="height: 350px; overflow-y: auto; font-size: 0.9rem;">';
$newChatBoxDef = '<div class="card-body bg-light" id="flowyChatBox" style="height: 350px; overflow-y: auto; font-size: 0.8rem;">';
$content = str_replace($oldChatBoxDef, $newChatBoxDef, $content);

// 2. Reduce the font-size in the dynamically injected HTML response bubbles
// AI bubble
$oldResponseDiv = 'font-size: 0.9rem; display: inline-block;"';
$newResponseDiv = 'font-size: 0.8rem; display: inline-block;"';
$content = str_replace($oldResponseDiv, $newResponseDiv, $content);

// 3. Make sure the headers generated by the markdown parser scale down nicely
$oldH6 = '<h6 class="mt-3 mb-1 fw-bold text-primary border-bottom pb-1">$1</h6>';
$newH6 = '<h6 class="mt-3 mb-1 fw-bold text-primary border-bottom pb-1" style="font-size: 0.85rem;">$1</h6>';
$content = str_replace($oldH6, $newH6, $content);

file_put_contents($layoutPath, $content);

echo "Font sizes reduced in Chat!\n";
