const fs = require('fs');
let content = fs.readFileSync('resources/views/profile/index.blade.php', 'utf8');

const dict = {
    'Seccin': 'Sección',
    'seccin': 'sección',
    'Suscripcin': 'Suscripción',
    'suscripcin': 'suscripción',
    'Informacin': 'Información',
    'informacin': 'información',
    'Facturacin': 'Facturación',
    'facturacin': 'facturación',
    'Estadsticas': 'Estadísticas',
    'estadsticas': 'estadísticas',
    'Contrasea': 'Contraseña',
    'contrasea': 'contraseña',
    'Electrnico': 'Electrónico',
    'electrnico': 'electrónico',
    'Bsico': 'Básico',
    'bsico': 'básico',
    'Mximo': 'Máximo',
    'mximo': 'máximo',
    'ltima': 'última',
    'Ltima': 'Última',
    'Adhesin': 'Adhesión',
    'adhesin': 'adhesión',
    'Lgicos': 'Lógicos',
    'lgicos': 'lógicos',
    'Fsicos': 'Físicos',
    'fsicos': 'físicos',
    'Perodo': 'Período',
    'perodo': 'período',
    'Mnimo': 'Mínimo',
    'mnimo': 'mínimo',
    'Crtico': 'Crítico',
    'crtico': 'crítico',
    'Configuracin': 'Configuración',
    'configuracin': 'configuración',
    'Renovacin': 'Renovación',
    'renovacin': 'renovación',
    'Telemetra': 'Telemetría',
    'telemetra': 'telemetría',
    'Aadir': 'Añadir',
    'aadir': 'añadir',
    'Ests ': 'Estás ',
    'ests ': 'estás ',
    ' Accin': ' Acción',
    ' accin': ' acción',
    'Eliminarn': 'Eliminarán',
    'eliminarn': 'eliminarán',
    'Podrs': 'Podrás',
    'podrs': 'podrás',
    'Emisin': 'Emisión',
    'emisin': 'emisión',
    'Requers': 'Requerís',
    'requers': 'requerís',
    'Despus': 'Después',
    'despus': 'después',
    'Condicin': 'Condición',
    'condicin': 'condición',
    'Expiracin': 'Expiración',
    'expiracin': 'expiración',
    'Confirmacin': 'Confirmación',
    'confirmacin': 'confirmación',
    'Duracin': 'Duración',
    'duracin': 'duración',
    'Funcin': 'Función',
    'funcin': 'función',
    'Botn': 'Botón',
    'botn': 'botón',
    'Edicin': 'Edición',
    'edicin': 'edición',
    'Asociacin': 'Asociación',
    'asociacin': 'asociación',
    'Versin': 'Versión',
    'versin': 'versión',
    'Crdito': 'Crédito',
    'crdito': 'crédito',
    'Dbito': 'Débito',
    'dbito': 'débito',
    'Descripcin': 'Descripción',
    'descripcin': 'descripción',
    'Direccin': 'Dirección',
    'direccin': 'dirección',
    'Ubicacin': 'Ubicación',
    'ubicacin': 'ubicación',
    'Tambin': 'También',
    'tambin': 'también',
    'Envo ': 'Envío ',
    'envo ': 'envío ',
    'Complet ': 'Completá ',
    ' pgina': ' página',
    ' Pgina': ' Página'
};

for (const [key, value] of Object.entries(dict)) {
    content = content.replace(new RegExp(key, 'g'), value);
}

content = content.replace(/B\s{2,}ajar/g, 'Bajar');

fs.writeFileSync('resources/views/profile/index.blade.php', content, 'utf8');
console.log('Done replacement');
